services:
  - type: web
    name: student-success-hub-api
    runtime: python
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "flask db upgrade && gunicorn run:app"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: student-success-hub-db
          property: connectionString
      - key: FRONTEND_URL
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_DEFAULT_SENDER
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false

databases:
  - name: student-success-hub-db
    plan: starter
